const http = require('http');
const url = require('url');
const generate = require('./modules/index.js');

const data = {
  tableName: 'base_area',
  tableComment: '字典',
  fileUrl: '/sys/dict',
  parentRouter: '/sys',
  router: '/dict',
  chinaValue: '字典',
  engValue: 'dict',
  tableInfo: [
    {
      editFlag: '0',
      componentType: 'Input',
      columnLength: 32,
      listFlag: '0',
      publicFlag: '1',
      scale: 0,
      sort: 1,
      primaryFlag: '0',
      javaType: 'String',
      columnType: 'CHAR',
      queryFlag: '0',
      notNullFlag: '1',
      insertFlag: '0',
      tableColumn: 'id',
      javaName: 'id',
      columnName: 'id',
      component: { type: 'Input' },
    },
    {
      editFlag: '1',
      componentType: 'Input',
      columnLength: 64,
      listFlag: '1',
      publicFlag: '0',
      scale: 0,
      sort: 2,
      primaryFlag: '0',
      javaType: 'String',
      columnType: 'VARCHAR',
      queryFlag: '1',
      notNullFlag: '1',
      insertFlag: '1',
      tableColumn: 'code',
      javaName: 'code',
      columnName: '编码',
      component: { type: 'Input' },
    },
    {
      editFlag: '1',
      componentType: 'Input',
      columnLength: 50,
      listFlag: '1',
      publicFlag: '0',
      scale: 0,
      sort: 3,
      primaryFlag: '0',
      javaType: 'String',
      columnType: 'VARCHAR',
      queryFlag: '1',
      notNullFlag: '1',
      insertFlag: '1',
      tableColumn: 'name',
      javaName: 'name',
      columnName: '名称',
      component: { type: 'Input' },
    },
    {
      editFlag: '1',
      componentType: 'Input',
      columnLength: 100,
      listFlag: '1',
      publicFlag: '0',
      scale: 0,
      sort: 5,
      primaryFlag: '1',
      javaType: 'String',
      columnType: 'VARCHAR',
      queryFlag: '1',
      notNullFlag: '0',
      insertFlag: '1',
      tableColumn: 'remark',
      javaName: 'remark',
      columnName: '备注',
      component: {
        type: 'Select',
        dataForm: '1',
        column: '',
        dataSource: [
          { value: '0', label: '备注0' },
          { value: '1', label: '备注1' },
          { value: '2', label: '备注2' },
        ],
      },
    },
    {
      editFlag: '1',
      componentType: 'Input',
      columnLength: 64,
      listFlag: '1',
      publicFlag: '0',
      scale: 0,
      sort: 6,
      primaryFlag: '1',
      javaType: 'String',
      columnType: 'VARCHAR',
      queryFlag: '1',
      notNullFlag: '0',
      insertFlag: '0',
      tableColumn: 'supcode',
      javaName: 'supcode',
      columnName: '上级编码',
      component: { type: 'Input' },
    },
    {
      editFlag: '1',
      componentType: 'Input',
      columnLength: 50,
      listFlag: '1',
      publicFlag: '0',
      scale: 0,
      sort: 7,
      primaryFlag: '1',
      javaType: 'String',
      columnType: 'VARCHAR',
      queryFlag: '1',
      notNullFlag: '1',
      insertFlag: '1',
      tableColumn: 'supname',
      javaName: 'supname',
      columnName: '上级名称',
      component: {
        type: 'Select',
        dataForm: '2',
        column: 'dictType',
      },
    },
    {
      editFlag: '1',
      componentType: 'Input',
      columnLength: 650,
      listFlag: '1',
      publicFlag: '0',
      scale: 0,
      sort: 8,
      primaryFlag: '1',
      javaType: 'String',
      columnType: 'VARCHAR',
      queryFlag: '1',
      notNullFlag: '0',
      insertFlag: '0',
      tableColumn: 'supcodes',
      javaName: 'supcodes',
      columnName: '上级编码集合,多个逗号分割',
      component: { type: 'Input' },
    },
    {
      editFlag: '1',
      componentType: 'Input',
      columnLength: 550,
      listFlag: '1',
      publicFlag: '0',
      scale: 0,
      sort: 9,
      primaryFlag: '1',
      javaType: 'String',
      columnType: 'VARCHAR',
      queryFlag: '1',
      notNullFlag: '0',
      insertFlag: '0',
      tableColumn: 'supnames',
      javaName: 'supnames',
      columnName: '上级名称集合,多个逗号分割',
      component: { type: 'Input' },
    },
    {
      editFlag: '0',
      componentType: 'Input',
      columnLength: 1,
      listFlag: '0',
      publicFlag: '1',
      scale: 0,
      sort: 10,
      primaryFlag: '0',
      javaType: 'String',
      columnType: 'CHAR',
      queryFlag: '0',
      notNullFlag: '1',
      insertFlag: '0',
      tableColumn: 'del_flag',
      javaName: 'delFlag',
      columnName: '删除标识(1:已删除,0:正常)',
      component: { type: 'Input' },
    },
    {
      editFlag: '1',
      componentType: 'Input',
      columnLength: 19,
      listFlag: '0',
      publicFlag: '1',
      scale: 0,
      sort: 11,
      primaryFlag: '0',
      javaType: 'Date',
      columnType: 'DATETIME',
      queryFlag: '1',
      notNullFlag: '1',
      insertFlag: '1',
      tableColumn: 'add_time',
      javaName: 'addTime',
      columnName: '创建时间',
      component: { type: 'DatePicker_datetime' },
    },
    {
      editFlag: '0',
      componentType: 'Input',
      columnLength: 64,
      listFlag: '0',
      publicFlag: '1',
      scale: 0,
      sort: 12,
      primaryFlag: '0',
      javaType: 'String',
      columnType: 'VARCHAR',
      queryFlag: '0',
      notNullFlag: '1',
      insertFlag: '0',
      tableColumn: 'add_user_code',
      javaName: 'addUserCode',
      columnName: '创建者',
      component: { type: 'Input' },
    },
    {
      editFlag: '0',
      componentType: 'Input',
      columnLength: 250,
      listFlag: '0',
      publicFlag: '1',
      scale: 0,
      sort: 13,
      primaryFlag: '0',
      javaType: 'String',
      columnType: 'VARCHAR',
      queryFlag: '0',
      notNullFlag: '1',
      insertFlag: '0',
      tableColumn: 'add_mark',
      javaName: 'addMark',
      columnName: '新增备注',
      component: { type: 'Input' },
    },
    {
      editFlag: '0',
      componentType: 'Input',
      columnLength: 19,
      listFlag: '0',
      publicFlag: '1',
      scale: 0,
      sort: 14,
      primaryFlag: '1',
      javaType: 'Date',
      columnType: 'DATETIME',
      queryFlag: '0',
      notNullFlag: '0',
      insertFlag: '0',
      tableColumn: 'upd_time',
      javaName: 'updTime',
      columnName: '更新时间',
      component: { type: 'Input' },
    },
    {
      editFlag: '1',
      componentType: 'Input',
      columnLength: 64,
      listFlag: '0',
      publicFlag: '1',
      scale: 0,
      sort: 15,
      primaryFlag: '1',
      javaType: 'String',
      columnType: 'VARCHAR',
      queryFlag: '1',
      notNullFlag: '1',
      insertFlag: '1',
      tableColumn: 'upd_user_code',
      javaName: 'updUserCode',
      columnName: '更新者',
      component: { type: 'InputNumber' },
    },
    {
      editFlag: '0',
      componentType: 'Input',
      columnLength: 250,
      listFlag: '0',
      publicFlag: '1',
      scale: 0,
      sort: 16,
      primaryFlag: '1',
      javaType: 'String',
      columnType: 'VARCHAR',
      queryFlag: '0',
      notNullFlag: '0',
      insertFlag: '0',
      tableColumn: 'upd_mark',
      javaName: 'updMark',
      columnName: '更新备注',
      component: { type: 'Input' },
    },
  ],
  hasPage: '1',
  menuName: [{ type: 'zh-CN', name: '字典' }, { type: 'en_US', name: 'dict' }],
};

http
  .createServer(function(request, response) {
    try {
      const pathName = url.parse(request.url).pathname;
      if (pathName === '/createFile') {
        generate.generateCodeHandle(data);

        // let data = '';
        // request.on('data', chunk => {
        //   data += chunk;
        //   generate.generateCodeHandle(JSON.parse(data));
        //   response.writeHead(200, { 'Content-Type': 'text/plain' });
        //   response.write('successful');
        //   response.end();
        // });
      }
    } catch (e) {
      console.log(e);
    }
  })
  .listen(9229);

// chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/6d9718e6-f366-4675-aff0-826def458b08
